// src/main.jsx (or src/index.js)

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

// !!! CRUCIAL LINE !!!
// This imports the CSS generated by Tailwind and makes it available to the app.
import './index.css'; 

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);